My_diplom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
]

homepage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.urls import reverse_lazy
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.forms.utils import ErrorList


app_name = 'homepage'


class MyHackedPassView(auth_views.PasswordChangeView):
    success_url = reverse_lazy('homepage:password_change_done')


urlpatterns = [
    path('find_master/', views.find_master, name='find_master'),
    path('<int:id_>/',
         views.people_details,
         name='people_details'),
    path('', views.start_page, name='start_page'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='profile'),
    path('edit/', views.edit_profile, name='edit'),
    path('password-change/', MyHackedPassView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('registration_confirmation/', views.registration_confirmation,
         name='registration_confirmation'),
    path('create_profile/', views.create_profile, name='create_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class ProfileUser(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='user/%Y/%m/%d', blank=True)
    first_name = models.CharField(max_length=90, blank=True)
    last_name = models.CharField(max_length=90, blank=True)
    name_organization = models.CharField(max_length=90, blank=True)
    type_service = models.CharField(max_length=50, blank=True)
    price = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=90, blank=True)
    link_to_instagram = models.TextField(blank=True)
    contact_details = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('homepage:people_details',
                       args=[self.id])

    def __str__(self):
        return f'{self.user.username} profile'


class Comment(models.Model):
    profile = models.ForeignKey(ProfileUser,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name = models.CharField(max_length=90)
    email = models.EmailField()
    body = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.profile}'

homepage/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User


class EmailMaterialForm(forms.Form):
    name = forms.CharField(max_length=250)
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'email', 'body', 'rating')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.ProfileUser
        exclude = ['user']


class ProfileFilterForm(forms.Form):
    min_price = forms.IntegerField(required=False)
    max_price = forms.IntegerField(required=False)

homepage/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import ProfileUser
from .models import Comment
from . import forms
from django.db.models import Q
from django.db.models import Avg
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def find_master(request):
    search_query = request.GET.get('search', '')
    filter_price = forms.ProfileFilterForm(request.GET)
    if search_query:
        people = ProfileUser.objects.filter(
            Q(type_service__icontains=search_query) | Q(
                address__icontains=search_query))
    else:
        people = ProfileUser.objects.all()

    if filter_price.is_valid():
        if filter_price.cleaned_data["min_price"]:
            people = ProfileUser.objects.filter(
                price__gte=filter_price.cleaned_data["min_price"])
        if filter_price.cleaned_data["max_price"]:
            people = ProfileUser.objects.filter(
                price__lte=filter_price.cleaned_data["max_price"])
    else:
        people = ProfileUser.objects.all()
    return render(request,
                  'people/find_master.html',
                  {"people": people,
                   "filter_price": filter_price,
                   }
                  )


def people_details(request, id_):
    profile = get_object_or_404(ProfileUser,
                                id=id_,
                                )
    reviews = Comment.objects.filter(profile=id_)
    average = reviews.aggregate(Avg('rating'))['rating__avg']
    if average is None:
        average = 0
    average = round(average, 2)

    if request.method == 'POST':
        comment_form = forms.CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.profile = profile
            new_comment.save()
            return redirect(profile)
    else:
        comment_form = forms.CommentForm()
    return render(request,
                  'people/detail.html',
                  {'profile': profile,
                   'comment_form': comment_form,
                   'average': average,
                   })


def start_page(request):
    return render(request,
                  'people/start_page.html',
                  )


def registration_confirmation(request):
    return render(request,
                  'registration/registration_confirmation.html')


def register(request):
    if request.method == 'POST':
        user_form = forms.UserRegistrationForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            ProfileUser.objects.create(user=new_user)
            return render(request, 'register_done.html',
                          {'new_user': new_user})
    else:
        user_form = forms.UserRegistrationForm()
    return render(request, 'register.html', {'user_form': user_form})


@login_required
def view_profile(request):
    return render(request, 'profile.html', {'user': request.user})


@login_required
def create_profile(request):
    return render(request, 'create_profile.html')


@login_required
def edit_profile(request):
    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST,
                                       instance=request.user,
                                       )
        profile_form = forms.ProfileEditForm(request.POST,
                                             instance=request.user.profileuser,
                                             files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return render(request, 'profile.html', {'user': request.user})

    user_form = forms.UserEditForm(instance=request.user)
    profile_form = forms.ProfileEditForm(instance=request.user.profileuser)
    return render(request,
                  'edit.html',
                  {'profile_form': profile_form,
                   'user_form': user_form})

homepage/templates/people/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ profile.first_name |add:profile.last_name }} {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="text-center col-xs-12" style="margin-top: 30px;">
            <a class="btn btn-lg btn-warning btn-block" href="{% url 'homepage:find_master' %}">Вернуться к поиску</a>
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row">
        <div class="col-3 pt-5">
            {% if profile.photo %}
                <p><img src="{{ profile.photo.url }}" alt="alt text" width="250" height="250" class="round"></p>
            {% else %}
                <p><img src="{% static "img/static_avatar.png" %}" alt="alt text" width="250" height="250" class="round"/></p>
             {% endif %}
        </div>
        <div class="col-4 pt-5">
            <p><b>Имя и фамилия:</b> {{ profile.first_name }} {{ profile.last_name }}</p>
            <p><b>Название организации:</b> {{ profile.name_organization }}</p>
            <p><b>Вид услуги:</b> {{ profile.type_service }}</p>
            <p><b>Цена:</b> {{ profile.price }}</p>
            <p><b>Адрес оказания услуг:</b> {{ profile.address }}</p>
            <p><b>Ссылка инстаграмм:</b> {{ profile.link_to_instagram}}</p>
            <p><b>Контактные данные:</b> {{ profile.contact_details}}</p>
            <p><b>Оценка:</b> {{ average }}/5</p>
        </div>
        <div class="col-5 pt-5">
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ comment_form.errors }}
                <div class="container">
                    <p><b>Оставить комментарий</b></p>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <p><label for='{{ comment_form.name }}'></label>
                                <input type="text" class="form-control"  placeholder="Имя" name="name"/></p>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <p><label for='{{ comment_form.email }}'></label>
                                <input type="email" class="form-control"  placeholder="Email" name="email" required/></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <p><label for='{{ comment_form.body }}'></label>
                            <input type="text" class="form-control" style="height: 100px" placeholder="Ваш комментарий" required name="body"/></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2">
                            <p class="font-weight-bold" style="width: 102px;">Ваша оценка</p>
                        </div>
                        <div class="rating-area col-10" style="margin-top: -5px;">
                            <input type="radio" id="star5" name="rating" value="5"><label for="star5"></label>
                            <input type="radio" id="star4" name="rating" value="4"><label for="star4"></label>
                            <input type="radio" id="star3" name="rating" value="3"><label for="star3"></label>
                            <input type="radio" id="star2" name="rating" value="2"><label for="star2"></label>
                            <input type="radio" id="star1" name="rating" value="1"><label for="star1"></label>
                        </div>
                    </div>
                    <div class="text-center col-xs-12">
                        <input type="submit" class="btn btn-lg btn-warning btn-block" value="Отправить комментарий" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<hr>
{% with profile.comments.count as total_comments %}
<h3 class="title-comments" style="margin-left: 40px;">{{ total_comments }} комментариев</h3><hr>
{% endwith %}
<div class="container">
    <div class="row">
        {% for comment in profile.comments.all %}
        <div class="col-6">
            <ul class="media-list">
                <li class="media">
                    <div class="media-body">
                        <div class="media-heading">
                            <div class="author">{{ comment.name }}</div>
                            <div class="metadata">
                                <span class="date">{{ comment.created }}</span>
                            </div>
                        </div>
                        <div class="media-text text-justify">{{ comment.body }}</div><br>
                        <div class="media-text text-justify">
                            {% if comment.rating == None %}
                            <h6>Оценки нет</h6>
                            {% else %}
                            <h6>Оценка: {{ comment.rating }}</h6>
                            {% endif %}
                        </div>
                    </div>
                </li>
            </ul><hr>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

homepage/templates/people/find_master.html
{% extends "base.html" %}
{% load static %}
{% block title %} START PAGE {% endblock %}
{% block content %}
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<form class="form-inline mt-2 mt-md-0">
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-8">
                <input class="form-control mr-sm-2" type="text" placeholder="Поиск:" name="search">
                <button class="btn-find btn btn-outline-warning my-2 my-sm-0" style="border-color: #ffc107;" type="submit">Поиск</button>
            </div>
            <div class="col-4">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <button class="dropdown-toggle btn-find btn btn-outline-warning my-2 my-sm-0" data-toggle="dropdown" style="border-color: #ffc107;" type="button">Сортировать по цене</button>
                        <div class="dropdown-menu">
                            <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for='{{ filter_price.min_price }}'></label>
                                    <div class="col-lg-11">
                                        <input type="number" class="form-control" name="min_price" placeholder="От" style="margin-bottom: 5px">
                                    </div>
                                </div><br>
                                <div class="form-group">
                                    <label for='{{ filter_price.max_price }}'></label>
                                    <div class="col-lg-11">
                                        <input type="number" class="form-control" name="max_price" placeholder="До" style="margin-bottom: 5px">
                                    </div>
                                </div><br>
                                <div class="form-group">
                                    <div class="col-lg-11">
                                        <button type="submit" class="btn btn-default">Сортировать</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</form>

<div class="row row-cols-1 row-cols-md-2" >
{% for person in people %}
  <div class="col-4 mb-4">
    <div class="card mb-4 shadow-sm">
        {% if person.photo %}
            <img src="{{ person.photo.url }}" class="card-img-top" alt="Загрузка фото">
        {% else %}
            <p><img src="{% static "img/static_avatar.png" %}" class="card-img-top" alt="Загрузка фото"/></p>
        {% endif %}
      <div class="card-body" >
        <h5 class="card-title">{{ person.first_name}} {{person.last_name }}</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Цена:</b> {{ person.price }}</li>
            <li class="list-group-item"><b>Контактная информация:</b> {{ person.contact_details }}</li>
            <li class="list-group-item"><b>Адрес:</b> {{ person.address }}</li>
            <li class="list-group-item"><a href="{{ person.get_absolute_url }}" class="btn btn-warning">Подробнее</a></li>
        </ul>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

homepage/templates/people/start_page.html
{% extends "base.html" %}

{% block title %} START PAGE {% endblock %}

{% block content %}
    <div class="general-container">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h2>Наше приложение поможет вам найти подходящего мастера</h2>
        <p class="lead">
          <a class="btn-start btn btn-outline-warning btn-lg " href="{% url 'homepage:find_master' %}">Поиск мастера</a>
        </p>
    </div>
    </div>
{% endblock %}