My_diplom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
]

homepage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.urls import reverse_lazy
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.forms.utils import ErrorList


app_name = 'homepage'


class MyHackedPassView(auth_views.PasswordChangeView):
    success_url = reverse_lazy('homepage:password_change_done')


urlpatterns = [
    path('find_master/', views.find_master, name='find_master'),
    path('<int:id_>/',
         views.people_details,
         name='people_details'),
    path('', views.start_page, name='start_page'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='profile'),
    path('edit/', views.edit_profile, name='edit'),
    path('password-change/', MyHackedPassView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('registration_confirmation/', views.registration_confirmation,
         name='registration_confirmation'),
    path('create_profile/', views.create_profile, name='create_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class ProfileUser(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='user/%Y/%m/%d', blank=True)
    first_name = models.CharField(max_length=90, blank=True)
    last_name = models.CharField(max_length=90, blank=True)
    name_organization = models.CharField(max_length=90, blank=True)
    type_service = models.CharField(max_length=50, blank=True)
    price = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=90, blank=True)
    link_to_instagram = models.TextField(blank=True)
    contact_details = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('homepage:people_details',
                       args=[self.id])

    def __str__(self):
        return f'{self.user.username} profile'


class Comment(models.Model):
    profile = models.ForeignKey(ProfileUser,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name = models.CharField(max_length=90)
    email = models.EmailField()
    body = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.profile}'

homepage/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User


class EmailMaterialForm(forms.Form):
    name = forms.CharField(max_length=250)
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'email', 'body', 'rating')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.ProfileUser
        exclude = ['user']


class ProfileFilterForm(forms.Form):
    min_price = forms.IntegerField(required=False)
    max_price = forms.IntegerField(required=False)

homepage/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import ProfileUser
from .models import Comment
from . import forms
from django.db.models import Q
from django.db.models import Avg
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def find_master(request):
    search_query = request.GET.get('search', '')
    filter_price = forms.ProfileFilterForm(request.GET)
    if search_query:
        people = ProfileUser.objects.filter(
            Q(type_service__icontains=search_query) | Q(
                address__icontains=search_query))
    else:
        people = ProfileUser.objects.all()

    if filter_price.is_valid():
        if filter_price.cleaned_data["min_price"]:
            people = ProfileUser.objects.filter(
                price__gte=filter_price.cleaned_data["min_price"])
        if filter_price.cleaned_data["max_price"]:
            people = ProfileUser.objects.filter(
                price__lte=filter_price.cleaned_data["max_price"])
    else:
        people = ProfileUser.objects.all()
    return render(request,
                  'people/find_master.html',
                  {"people": people,
                   "filter_price": filter_price,
                   }
                  )


def people_details(request, id_):
    profile = get_object_or_404(ProfileUser,
                                id=id_,
                                )
    reviews = Comment.objects.filter(profile=id_)
    average = reviews.aggregate(Avg('rating'))['rating__avg']
    if average is None:
        average = 0
    average = round(average, 2)

    if request.method == 'POST':
        comment_form = forms.CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.profile = profile
            new_comment.save()
            return redirect(profile)
    else:
        comment_form = forms.CommentForm()
    return render(request,
                  'people/detail.html',
                  {'profile': profile,
                   'comment_form': comment_form,
                   'average': average,
                   })


def start_page(request):
    return render(request,
                  'people/start_page.html',
                  )


def registration_confirmation(request):
    return render(request,
                  'registration/registration_confirmation.html')


def register(request):
    if request.method == 'POST':
        user_form = forms.UserRegistrationForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            ProfileUser.objects.create(user=new_user)
            return render(request, 'register_done.html',
                          {'new_user': new_user})
    else:
        user_form = forms.UserRegistrationForm()
    return render(request, 'register.html', {'user_form': user_form})


@login_required
def view_profile(request):
    return render(request, 'profile.html', {'user': request.user})


@login_required
def create_profile(request):
    return render(request, 'create_profile.html')


@login_required
def edit_profile(request):
    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST,
                                       instance=request.user,
                                       )
        profile_form = forms.ProfileEditForm(request.POST,
                                             instance=request.user.profileuser,
                                             files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return render(request, 'profile.html', {'user': request.user})

    user_form = forms.UserEditForm(instance=request.user)
    profile_form = forms.ProfileEditForm(instance=request.user.profileuser)
    return render(request,
                  'edit.html',
                  {'profile_form': profile_form,
                   'user_form': user_form})

homepage/templates/base.html
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MY DEFAULT TITLE{% endblock %}</title>
    <link href="{% static "styles.css" %}" rel="stylesheet">
</head>
<body>
{% block menu %}
<div class="fixed-top d-flex flex-column flex-md-row align-items-center px-md-4 bd-black border-bottom shadow-sm">
    <a class="text-dark m-1 my-0 mr-md-auto font-weight-normal" href="{% url "homepage:start_page" %}">Хорошее приложение</a>
{#  <h5 class="my-0 mr-md-auto font-weight-normal">Хорошее приложение</h5>#}
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="text-dark m-1" href="{% url "homepage:start_page" %}">Главная</a>
    <a class="text-dark m-1" href="#">Обучение</a>
    <a class="text-dark m-1" href="#">О проекте</a>
    {% if request.user.is_authenticated %}
        <a class="text-dark m-1" href="{% url "homepage:profile" %}">Профиль</a>
        <a class="text-dark m-1" href="{% url "homepage:logout" %}">Выйти</a>
    {% else %}
        <a class="btn btn-outline-dark p-1 m-1" href="{% url 'homepage:login' %}">Вход</a>
        <a class="btn btn-outline-dark p-1" href="{% url 'homepage:registration_confirmation' %}">Регистрация</a><br>
    {% endif %}
  </nav>
</div><br>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

homepage/templates/create_profile.html
{% extends "base.html" %}

{% block title %}Create link{% endblock %}
{% block content %}
    <br>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="text-center">Добро пожаловать! Вы вошли в систему, однако ваш профиль пуст. Давайте заполним его:</h3>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="text-center col-xs-12 mr-1">
                <a class="btn btn-lg btn-warning btn-block" href="{% url 'homepage:edit' %}">Редактировать профиль</a>
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit your account{% endblock %}

{% block content %}
<div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Редактирование профиля</h3>
            <form action="." method="post" enctype="multipart/form-data"  style="margin-top:20px">
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ user_form.email }}'></label>
                            <input type="email" class="form-control"  placeholder="email@email.com" name="email" value='{{ user.profileuser.user.email }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="custom-file pb-5">
                        <p><label class="custom-file-label" for='id_photo'>Добавить фотографию</label>
                            <input type="file" class="custom-file-input" accept="image/*" name="photo"  id="id_photo"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.first_name }}'></label>
                            <input type="text" class="form-control" placeholder="Введите имя" name="first_name" required value='{{ user.profileuser.first_name }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.last_name }}'></label>
                            <input type="text" class="form-control" placeholder="Введите фамилию" name="last_name" required value='{{ user.profileuser.last_name }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.name_organization }}'></label>
                            <input type="text" class="form-control" placeholder="Введите название организации" name="name_organization" value='{{ user.profileuser.name_organization }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.type_service }}'></label>
                            <input type="text" class="form-control" placeholder="Введите вид услуги" name="type_service" value='{{ user.profileuser.type_service }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.price }}'></label>
                            {% if user.profileuser.price == None %}
                                <input type="number" class="form-control" placeholder="Введите цену базового покрытия BYN" required name="price"/></p>
                            {% else %}
                                <input type="number" class="form-control" placeholder="Введите цену базового покрытия" name="price" required value='{{ user.profileuser.price }}'/></p>
                            {% endif %}
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.address }}'></label>
                            <input type="text" class="form-control" placeholder="Введите адресс" name="address" required value='{{ user.profileuser.address }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.link_to_instagram }}'></label>
                            <input type="url" class="form-control" placeholder="Добавьте ссылку instagram" name="link_to_instagram" value='{{ user.profileuser.link_to_instagram }}'/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ profile_form.contact_details }}'></label>
                            <input type="text" class="form-control" placeholder="Контактная информация" name="contact_details" value='{{ user.profileuser.contact_details }}'/></p>
                    </div>
                </div>

                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Сохранить изменения" />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-3 pt-5">
            {% if user.profileuser.photo %}
                <p><img src="{{ user.profileuser.photo.url }}" alt="alt text" width="250" height="250" class="round"></p>
            {% else %}
                <p><img src="{% static "img/static_avatar.png" %}" alt="alt text" width="250" height="250" class="round"/></p>
             {% endif %}
            <p><a href="{% url "homepage:edit" %}">Редактировать профиль</a></p>
            <p><a href="{% url "homepage:password_change" %}">Изменение пароля</a></p>
        </div>
        <div class="col-xs-9 pt-5 pl-5">
            <p><b>Имя и фамилия:</b> {{ user.profileuser.first_name }} {{ user.profileuser.last_name }}</p>
            <p><b>Название организации:</b> {{ user.profileuser.name_organization }}</p>
            <p><b>Вид услуг:</b> {{ user.profileuser.type_service }}</p>
            <p><b>Цена:</b> {{ user.profileuser.price }}</p>
            <p><b>Адрес оказания услуг:</b> {{ user.profileuser.address }}</p>
            <p><b>Ссылка инстаграмм:</b> {{ user.profileuser.link_to_instagram }}</p>
            <p><b>Контактные данные:</b> {{ user.profileuser.contact_details }}</p>
        </div>
    </div>
</div>

{% endblock %}

homepage/templates/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}
{% block content %}
<br><br>
 <div class="container container-register">
    <div class="row">
        <div class="col-12" style="padding-left: 30%; padding-right: 30%;">
            <h3 class="text-center">Регистрация</h3>
            <form action="." method="post"  style="margin-top:20px">
                {% csrf_token %}
                {{ user_form.errors }}
                <div class="col-xs-12">
                    <div class="form-group">
                         <p><label for='{{ user_form.username }}'></label>
                            <input type="text" class="form-control" placeholder="Введите логин" name="username" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ user_form.email }}'></label>
                            <input type="email" class="form-control" placeholder="Введите email" name="email" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ user_form.password }}'></label>
                            <input type="password" class="form-control" placeholder="Введите пароль" name="password" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <p><label for='{{ user_form.password2 }}'></label>
                            <input type="password" class="form-control" placeholder="Повторите пароль" name="password2" required autocomplete="off"/></p>
                    </div>
                </div>
                <div class="text-center col-xs-12">
                    <input type="submit" class="btn btn-lg btn-warning btn-block" value="Зарегистрироваться" />
                </div>
            </form>
        </div>
    </div>
 </div>
{% endblock %}

homepage/templates/register_done.html
{% extends "base.html" %}

{% block title %}Registration confirmation{% endblock %}
{% block content %}
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="text-center col-12 mr-1">
                <h3 >Здравствуйте {{ new_user.username }}! Вы зарегистрировались. Войдите в систему:</h3>
            </div><br>
            <div class="text-center col-xs-12 mr-1">
                <a class="btn btn-lg btn-warning btn-block" href="{% url 'homepage:login' %}">Войти</a>
            </div>
            <div class="text-center col-xs-12">
                <a class="btn btn-lg btn-warning btn-block" href="{% url "homepage:start_page" %}">Вернуться на главную</a>
            </div>
        </div>
    </div>

{% endblock %}